---
# Copyright 2016 Internet Solutions (Pty) Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# (c) 2016 Donovan Francesco <donovan.francesco@is.co.za>
# (c) 2016 Paul Stevens <paul.stevens@is.co.za>
- name: Ensure /etc/init.d/elasticsearch is absent
  file:
    path: /etc/init.d/elasticsearch
    state: absent
    force: yes

- name: Templatize /etc/hosts
  template:
    src: elasticsearch_hosts_file.j2
    dest: /etc/hosts
    mode: 0644
  register: os_elasticsearch_config_hosts
  when: elasticsearch_manage_hosts_file | bool
- name: Copy elasticsearch.yml to node
  template:
    src: elasticsearch.yml.j2
    dest: "{{ elasticsearch_etc_directory }}/elasticsearch.yml"
    owner: "{{ elasticsearch_system_user_name }}"
    group: "{{ elasticsearch_system_group_name }}"
    mode: 0644
    force: yes
  notify: Restart elasticsearch services

- name: Copy /etc/default/elasticsearch File for Instance
  template:
    src: elasticsearch_etc_default.j2
    dest: "/etc/default/{{ elasticsearch_program_name }}"
    mode: 0644
    force: yes
  notify: Restart elasticsearch services

- name: Copy Logging.yml File for Instance
  template:
    src: logging.yml.j2
    dest: "{{elasticsearch_etc_directory}}/logging.yml"
    owner: "{{ elasticsearch_system_user_name }}"
    group: "{{ elasticsearch_system_group_name }}"
    mode: 0644
    force: yes
  notify: Restart elasticsearch services

- name: Detect installed plugins
  shell: bin/plugin list chdir={{ elasticsearch_system_user_home }}
  changed_when: False
  register: elasticsearch_register_installed_plugins

- name: Delete plugins
  shell: bin/plugin remove {{ item.name }} chdir={{ elasticsearch_system_user_home }}
  when: item.delete is defined and item.delete and
        (item.name in elasticsearch_register_installed_plugins.stdout or
        item.name.split('/')[1] in elasticsearch_register_installed_plugins.stdout)
  with_items: elasticsearch_plugins
  notify: Restart elasticsearch services

- name: Install plugins by name
  shell: bin/plugin install {{ item.name }} chdir={{ elasticsearch_system_user_home }}
  when: (item.url is undefined or not item.url) and
        (item.delete is undefined or not item.delete) and
        not item.name.split('/')[1] in elasticsearch_register_installed_plugins.stdout
  with_items: elasticsearch_plugins
  notify: Restart elasticsearch services
  ignore_errors: true

- name: Install plugins by url
  shell: bin/plugin install {{ item.name }} -u {{ item.url }}
         chdir={{ elasticsearch_system_user_home }}
  when: item.url is defined and item.url and
        (item.delete is undefined or not item.delete) and
        not item.name in elasticsearch_register_installed_plugins.stdout
  with_items: elasticsearch_plugins
  notify: Restart elasticsearch services

- name: Restart ElasticSearch before proceeding
  meta: flush_handlers

- name: Wait for ElasticSearch port
  wait_for:
    host: "{{ ansible_ssh_host }}"
    port: "{{ elasticsearch_service_port }}"
  tags:
    - elasticsearch-post-install

- name: Setup Curator config file
  template:
    src: curator.yml.j2
    dest: "{{ curator_config }}"
    owner: "{{ elasticsearch_system_user_name }}"
    group: "{{ elasticsearch_system_group_name }}"
    mode: 0644
    force: yes
  tags:
    - [elasticsearch-post-install,curator]

- name: Setup Curator action file
  template:
    src: delete_indices.yml.j2
    dest: "{{ curator_action }}"
    owner: "{{ elasticsearch_system_user_name }}"
    group: "{{ elasticsearch_system_group_name }}"
    mode: 0644
    force: yes
  tags:
    - [elasticsearch-post-install,curator]

- name: Setup the ElasticSearch Curator cron job
  cron:
    name: "ElasticSearch Curator"
    minute: 0
    hour: 0
    user: "root"
    job: "/usr/local/bin/curator --config {{ curator_config }} {{ curator_action }}"
    cron_file: "elasticsearch_curator"
  tags:
    - elasticsearch-post-install
